name = "animeku-frontend"
main = "dist/index.html"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "ANIMEKU_BUCKET"
bucket_name = "animeku"  # Ganti dengan nama bucket Anda

# Untuk deploy static ke R2
[site]
bucket = "./dist"
